#   python evaluators/test.py \
#     --env_config configs/eval/nep/nep_longedge.yaml \
#     --model models/qtable-nep-longedge/iter_500
algo_name: qtable
env_type: nep

env:
  graph_path: graphs/long_edge.json
  enable_wait: false
  norm_reward: true
  norm_obs: false
  num_agents: 3
  init_positions: [0, 1, 2]
  episode_len: 100
  custom_configs:
    truncate_by_time: true

eval:
  seed: 42
  num_episodes: 10
  show_plot: false
