algo_name: qtable
env_type: nep

env:
  graph_path: graphs/simple_TSP_12.json
  enable_wait: false
  norm_reward: true
  norm_obs: false
  num_agents: 3
  init_positions: [0, 5, 11]
  episode_len: 300
  custom_configs:
    truncate_by_time: true