#   python evaluators/test.py --env_config configs/eval/suns/suns_SF.yaml --model models/a2c-suns-SF/final
env_type: suns

env:
  graph_path: graphs/SFcrimemap.json
  enable_wait: false
  norm_reward: true
  num_agents: 3
  init_positions: [0, 5, 11]
  episode_len: 3000
  custom_configs:
    truncate_by_time: true

eval:
  num_episodes: 10
  save_plot: evaluators/results/SF/a2c_suns/best_eval.png
  show_plot: false
  animation: true
  event_driven: false
  max_frames: 2000
