env_type: suns

env:
  graph_path: graphs/Chain10nodes9edges.json
  enable_wait: false
  norm_reward: true
  norm_obs: true
  num_agents: 4
  init_positions: [0, 3, 6, 9]
  episode_len: 100
  custom_configs:
    truncate_by_time: true

eval:
  num_episodes: 10
  save_plot: evaluators/results/chain10/a2c_suns/best_eval.png
  show_plot: false
  animation: true
  event_driven: true
  max_frames: 300
  log_action_logits: true
  log_action_logits_max_lines: 5
  action_logits_csv: evaluators/results/chain10/a2c_suns/action_logits.csv
  action_logits_active_only: true
