#   python evaluators/test.py --env_config configs/eval/masup/ippo_masup_longedge.yaml \
#                             --model models/xxx/final
env_type: masup

env:
  graph_path: graphs/long_edge.json
  enable_wait: true
  deltaT: 0.5
  num_agents: 3
  init_positions: [0, 1, 2]
  episode_len: 100
  custom_configs:
    T: 10.0
    role_imformation: decision
    truncate_by_time: true

eval:
  num_episodes: 10
  save_plot: evaluators/results/long_edge/ippo_masup/best_eval.png
  show_plot: false
  animation: true
  event_driven: true
  max_frames: 350
