env_type: masup

env:
  graph_path: graphs/SFcrimemap.json
  enable_wait: true
  deltaT: 200.0
  num_agents: 3
  init_positions: [0, 5, 11]
  episode_len: 3000
  edge_time_jitter: false
  custom_configs:
    truncate_by_time: true

eval:
  num_episodes: 10
  save_plot: evaluators/results/SF/masup/best_eval.png
  show_plot: false
  animation: true
  event_driven: true
  max_frames: 2000