env_type: masup

env:
  graph_path: graphs/SFcrimemap.json
  enable_wait: true
  deltaT: 20.0
  num_agents: 3
  init_positions: [0, 5, 11]
  episode_len: 300
  custom_configs:
    truncate_by_time: true