env_type: masup

env:
  graph_path: graphs/SFcrimemap.json
  enable_wait: true
  norm_reward: true
  deltaT: 20.0
  num_agents: 1
  init_positions: [0]
  episode_len: 3000
  custom_configs:
    T: 200.0
    role_imformation: decision
    reward_scale: 0.01
    truncate_by_time: true
    idi_scale: 0.05
    contribution_scale: 0.05

eval:
  num_episodes: 10
  save_plot: evaluators/results/SF/mappo_masup_a1/best_eval.png
  show_plot: false
  animation: true
  event_driven: true
  max_frames: 1500
  log_action_logits: true
  log_action_logits_max_lines: 5
  action_logits_csv: evaluators/results/SF/mappo_masup_a1/action_logits.csv
  action_logits_active_only: true
