env_type: masup

env:
  graph_path: graphs/grid.json
  enable_wait: true
  norm_reward: true
  deltaT: 0.5
  num_agents: 6
  init_positions: [1, 9, 17, 25, 33, 41]
  episode_len: 500
  edge_time_jitter: false
  custom_configs:
    T: 50.0
    role_imformation: decision
    reward_scale: 0.01
    truncate_by_time: true
    idi_scale: 0.05
    contribution_scale: 0.05

eval:
  num_episodes: 10
  save_plot: evaluators/results/grid/mappo_masup_pre/eval.png
  show_plot: false
  animation: true
  event_driven: true
  max_frames: 300
