# BBLA Q-table 评估配置 (TSP12)
# 用法:
#   python evaluators/test.py \
#     --env_config configs/eval/bbla_tsp12.yaml \
#     --model models/qtable-bbla/ep_1000 \
#     --num_episodes 10

algo_name: qtable
env_type: bbla

env:
  graph_path: graphs/simple_TSP_12.json
  enable_wait: false
  num_agents: 3
  init_positions: [0, 5, 11]
  episode_len: 300
  custom_configs:
    truncate_by_time: true
