# S4R1Env TSP12 评估配置
# 用法:
#   python evaluators/test.py --env_config configs/eval/s4r1_tsp12.yaml --model models/xxx/final

env_type: s4r1

env:
  graph_path: graphs/simple_TSP_12.json
  enable_wait: false
  num_agents: 3
  init_positions: [0, 5, 11]
  episode_len: 300
  custom_configs:
    truncate_by_time: true
    penalised_factor: 1.5

eval:
  num_episodes: 10
  save_plot: evaluators/results/TSP12/iql_s4r1/best_eval.png
  show_plot: False
  animation: True
  event_driven: False
  max_frames: 500
