env:
  graph_path: graphs/SFcrimemap.json
  num_agents: 3
  deltaT: 20.0
  init_positions: [0, 5, 11]
  episode_len: 3000

eval:
  num_episodes: 10
  save_plot: evaluators/results/SF/cc/CC_eval.png
  show_plot: false
  animation: false
  event_driven: true
  max_frames: 1500

algorithm_params:
  idleness_weight: 1.0
  distance_weight: 0.5
  distance_mode: edge
