env:
  graph_path: graphs/island.json
  num_agents: 6
  init_positions: [0, 10, 20, 30, 40, 49]
  episode_len: 500

eval:
  num_episodes: 10
  save_plot: evaluators/results/island/msp/MSP_eval.png
  show_plot: false
  animation: false
  event_driven: true
  max_frames: 1500

routes:
  - [0, 3, 6, 9, 0, 2, 8, 0]
  - [5, 10, 11, 5, 8, 4, 5, 0, 5]
  - [11, 7, 1, 11, 4, 10, 11, 5, 11]
