env:
  graph_path: graphs/SFcrimemap.json
  num_agents: 3
  deltaT: 20.0
  init_positions: [0, 5, 11]
  episode_len: 3000

eval:
  num_episodes: 10
  save_plot: evaluators/results/SF/msp/MSP_eval.png
  show_plot: false
  animation: false
  event_driven: true
  max_frames: 1500

routes:
  - [0, 3, 6, 9, 0, 2, 8, 0]
  - [5, 10, 11, 5, 8, 4, 5, 0, 5]
  - [11, 7, 1, 11, 4, 10, 11, 5, 11]
