method: bayes
metric:
  name: eval/wi
  goal: minimize

parameters:
  seed:
    value: 42
  lr:
    min: 0.00001
    max: 0.01
    distribution: log_uniform_values
  gamma:
    value: 0.999
  epsilon_start:
    values:
    - 0.2
    - 0.5
    - 1.0
  epsilon_end:
    value: 0.05
  save_interval:
    value: 1000
  epsilon_decay_steps:
    min: 8000000
    max: 15000000
    distribution: uniform

early_terminate:
  min_trial: 4
  min_steps: 10000000
  terminate_ratio: 0.5
  early_stop_iters: 200
  slope_horizons: [16, 64, 128]
  slope_threshold: 3.0e-5