env_type: magec

env:
  graph_path: graphs/island.json
  enable_wait: false
  norm_reward: true
  norm_obs: false
  num_agents: 6
  init_positions: [0, 10, 20, 30, 40, 49]
  episode_len: 500
  custom_configs:
    truncate_by_time: true
    alpha: 1
    beta: 0.5

eval:
  num_episodes: 10
  save_plot: evaluators/results/island/mappo_magec/best_eval.png
  show_plot: false
  animation: true
  event_driven: true
  max_frames: 1000
  log_action_logits: true
  log_action_logits_max_lines: 5
  action_logits_csv: evaluators/results/island/mappo_magec/action_logits.csv
  action_logits_active_only: true
