method: bayes
metric:
  name: eval/wi
  goal: minimize
parameters:
  seed:
    value: 42
  lr:
    min: 0.01
    max: 0.9
    distribution: log_uniform_values
  gamma:
    values:
    - 0.9
    - 0.99
    - 0.999
  epsilon_start:
    values:
    - 0.05
    - 0.1
    - 0.2
    - 0.5
  epsilon_end:
    min: 0.01
    max: 0.1
    distribution: uniform
  save_interval:
    value: 1000
  epsilon_decay_steps:
    min: 1000
    max: 500000000
    distribution: uniform
