env_config:
  graph_path: "graphs/grid.json"

  
  enable_wait: True
  deltaT: 1.0
  
  num_agents: 8
  # init_positions: [6, 12, 18, 24, 30, 36, 42, 48]
  
  episode_len: 1000

# env_config:
#   graph_path: "graphs/simple_TSP_12.json"
  
#   enable_wait: True
#   deltaT: 0.5
  
#   num_agents: 3
#   init_positions: [0, 5, 11]
  
#   episode_len: 1000 

  
custom_config:
  truncate_by_time: True


