env_config:
  graph_path: "graphs/simple_TSP_12.json"
  
  enable_wait: True
  deltaT: 0.5
  
  num_agents: 3
  
  episode_len: 300 # 默认是一个episode的step数,在MASUP环境中若truncate_by_time为True,则是一个episode的最大时间

  
custom_config:
  T: 20.0
  role_imformation: "agent-index"
  reward_scale: 0.01
  truncate_by_time: True
  idi_scale: 0.05
  contribution_scale: 0.05

