method: bayes

metric:
  name: env/wi_fromT
  goal: minimize

parameters:
  lr:
    min: 1.0e-6
    max: 1.0e-3
    distribution: log_uniform_values

  clip_range:
    min: 0.1
    max: 0.4
  vf_coef:
    min: 0.5
    max: 2.0
  ent_coef:
    min: 0.0
    max: 0.3
  gae_lambda:
    min: 0.9
    max: 1.0

  gamma:
    values: [0.97, 0.98, 0.99]

  use_value_norm:
    value: true

  num_steps:
    values: [512, 1024, 2048]
  minibatch_size:
    values: [512, 1024, 2048, 4096]
  update_epochs:
    values: [3, 5, 10]

  total_steps:
    value: 20000000

  save_interval:
    value: 500

  custom_configs.idi_scale:
    values: [0.0, 0.05, 0.1]
  custom_configs.contribution_scale:
    values: [0.0, 0.05, 0.1]
