method: random

metric:
  name: env/wi_fromT
  goal: minimize

parameters:
  actor_lr:
    min: 1.0e-6
    max: 3.0e-4
    distribution: log_uniform_values
  critic_lr:
    min: 1.0e-5
    max: 5.0e-3
    distribution: log_uniform_values

  clip_range:
    min: 0.05
    max: 0.3
  vf_coef:
    min: 0.5
    max: 2.0
  ent_coef:
    min: 0.0
    max: 0.05
  gae_lambda:
    min: 0.9
    max: 1.0

  gamma:
    value: 0.999

  use_value_norm:
    value: true

  num_steps:
    values: [2048, 4096, 8192]
  minibatch_size:
    values: [1024, 2048, 4096]
  update_epochs:
    values: [3, 5]

  total_steps:
    value: 50000000

  save_interval:
    value: 200

  custom_configs.idi_scale:
    values: [0.0, 0.05, 0.1]
  custom_configs.contribution_scale:
    values: [0.0, 0.05, 0.1]

  actor_path:
    value: models/imi-mappo-pre-masup-SF/imi_pre_masup_mlp_mappo_SF__1776830456_final/policy.pt
  critic_path:
    value: models/imi-mappo-pre-masup-SF/imi_pre_masup_mlp_mappo_SF__1776830456_final/critic.pt

early_terminate:
  min_trial: 6
  min_steps: 10000000
  terminate_ratio: 0.4
  early_stop_iters: 100
  slope_horizons: [8, 32, 64]
  slope_threshold: 1.0e-4
