method: bayes

metric:
  name: eval/wi_fromT
  goal: minimize

early_terminate:
  min_trial: 4
  min_steps: 15000000
  terminate_ratio: 0.5
  early_stop_iters: 100
  slope_horizons: [16, 64, 128]
  slope_threshold: 3.0e-5
  state_file: .sweep_es_mappo_masup_cumberland.json

parameters:
  seed:
    value: 42
  total_steps:
    value: 40000000
  actor_lr:
    min: 1.0e-6
    max: 5.0e-4
    distribution: log_uniform_values
  critic_lr:
    min: 1.0e-4
    max: 5.0e-3
    distribution: log_uniform_values
  clip_range:
    min: 0.05
    max: 0.25
  vf_coef:
    min: 0.4
    max: 0.8
  ent_coef:
    min: 0.0
    max: 0.08
  gae_lambda:
    value: 0.999
  gamma:
    value: 0.99
  use_value_norm:
    value: true
  num_steps:
    values: [2048, 4096]
  minibatch_size:
    values: [8192, 12288]
  update_epochs:
    values: [5, 10]
  save_interval:
    value: 300
  custom_configs.idi_scale:
    value: 0.1
  custom_configs.contribution_scale:
    value: 0.1
