#   python sweep.py --base-config configs/experiments/masup/vdppo_masup_grid.yaml \
#                   --sweep-config configs/sweep/masup/vdppo_masup_grid.yaml --count 32
method: bayes

metric:
  name: eval/wi_fromT
  goal: minimize

early_terminate:
  min_trial: 6
  min_steps: 10000000
  terminate_ratio: 0.4
  early_stop_iters: 100
  slope_horizons: [16, 64, 128]
  slope_threshold: 3.0e-5

parameters:
  seed:
    value: 42
  actor_lr:
    min: 1.0e-6
    max: 1.0e-3
    distribution: log_uniform_values

  q_lr:
    min: 1.0e-6
    max: 1.0e-3
    distribution: log_uniform_values

  clip_range:
    values: [0.15, 0.2, 0.25]

  ent_coef:
    min: 0.0
    max: 0.3

  vf_coef:
    values: [0.5, 1.0]

  gamma:
    value: 0.999

  gae_lambda:
    values: [0.9, 0.95, 0.99]

  tau:
    values: [0.001, 0.005]

  target_update_freq:
    value: 1

  mixer_embed_dim:
    value: 256

  data_chunk_length:
    value: 10

  num_steps:
    values: [512, 1024]

  minibatch_size:
    values: [2048, 4096]

  update_epochs:
    values: [3, 5]

  total_steps:
    value: 50000000

  save_interval:
    value: 500

early_terminate:
  min_trial: 6
  min_steps: 5000000
  terminate_ratio: 0.4
  early_stop_iters: 100
  slope_horizons: [8, 32, 64]
  slope_threshold: 1.0e-4
