#   python sweep.py --base-config configs/experiments/masup/vdppo_masup_SF.yaml \
#                   --sweep-config configs/sweep/masup/vdppo_masup_SF.yaml --count 40
method: bayes

metric:
  name: eval/wi_fromT
  goal: minimize

parameters:
  seed:
    value: 42

  actor_type:
    value: masup_mlp
  q_type:
    value: masup_vdppo_rnn

  actor_lr:
    min: 1.0e-6
    max: 0.0002
    distribution: log_uniform_values

  q_lr:
    min: 1.0e-6
    max: 0.0003
    distribution: log_uniform_values

  clip_range:
    min: 0.1
    max: 0.3

  ent_coef:
    min: 0.0
    max: 0.05

  vf_coef:
    min: 0.5
    max: 2.0

  gamma:
    value: 0.999

  gae_lambda:
    min: 0.9
    max: 1.0

  tau:
    min: 0.01
    max: 0.5
    distribution: log_uniform_values

  target_update_freq:
    value: 1

  mixer_embed_dim:
    value: 256

  data_chunk_length:
    value: 10

  minibatch_size:
    values: [2048, 4096, 8192]

  update_epochs:
    values: [3, 5]

  num_steps:
    values: [2048, 4096]

  total_steps:
    value: 40000000

  save_interval:
    value: 500

early_terminate:
  min_trial: 4
  min_steps: 10000000
  terminate_ratio: 0.5
  early_stop_iters: 100
  slope_horizons: [16, 64, 128]
  slope_threshold: 3.0e-5
