# WandB Sweep 配置文件
# 用法: python sweep.py --base-config configs/experiments/mappo_tsp12_imi.yaml \
#                       --sweep-config configs/sweep/mappo_hparam.yaml

method: random

metric:
  name: env/wi
  goal: minimize

early_terminate:
  type: median_stopping_rule
  min_iter: 800
  min_samples_to_check: 8

parameters:
  # ---- algo params (映射到 MAPPOParams) ----
  actor_lr:
    min: 0.00001
    max: 0.001
    distribution: log_uniform_values
  critic_lr:
    min: 0.0001
    max: 0.003
    distribution: log_uniform_values

  clip_range:
    min: 0.1
    max: 0.4
  vf_coef:
    min: 0.1
    max: 2.0
  ent_coef:
    min: 0.0
    max: 0.3
  gae_lambda:
    min: 0.9
    max: 1.0
  gamma:
    value: 0.999

  # ---- training params (映射到 OnPolicyTrainerConfig) ----
  minibatch_size:
    values: [256, 512, 1024, 2048]
  update_epochs:
    values: [3, 5, 10]
  num_steps:
    values: [1024, 2048, 4096]
  total_steps:
    value: 50000000
  save_interval:
    value: 750

  custom_configs.idi_scale:
    values: [0.01, 0.05, 0.1]
  custom_configs.contribution_scale:
    values: [0.01, 0.05, 0.1]

# method: bayes

# metric:
#   name: env/wi
#   goal: minimize

# early_terminate:
#   type: median_stopping_rule
#   min_iter: 300
#   min_samples_to_check: 8

# parameters:
#   # ---- algo params (映射到 MAPPOParams) ----
#   actor_lr:
#     min: 0.00003
#     max: 0.003
#     distribution: log_uniform_values
#   critic_lr:
#     min: 0.00001
#     max: 0.001
#     distribution: log_uniform_values

#   clip_range:
#     min: 0.05
#     max: 0.3
#   vf_coef:
#     min: 0.1
#     max: 0.6
#   ent_coef:
#     min: 0.0
#     max: 0.1
#   gae_lambda:
#     min: 0.95
#     max: 1.0
#   gamma:
#     value: 0.999

#   # ---- training params (映射到 OnPolicyTrainerConfig) ----
#   minibatch_size:
#     values: [256, 512, 1024, 2048, 4096]
#   update_epochs:
#     values: [5, 8, 10]
#   num_steps:
#     values: [2048, 4096, 6144]
#   total_steps:
#     value: 50000000
#   save_interval:
#     value: 500

#   custom_configs.idi_scale:
#     values: [0.01, 0.05, 0.1]
#   custom_configs.contribution_scale:
#     values: [0.01, 0.05, 0.1]
