#   python evaluators/test.py --env_config configs/eval/masupgnn/masupgnn_SF.yaml --model models/xxx/final
env_type: masup_gnn

env:
  graph_path: graphs/SFcrimemap.json
  enable_wait: true
  norm_reward: true
  deltaT: 20.0
  num_agents: 3
  init_positions: [0, 5, 11]
  episode_len: 3000
  custom_configs:
    T: 200.0
    role_imformation: decision
    truncate_by_time: true
    node_feat_dim: 2
    edge_feat_dim: 1
    global_feat_dim: 2

eval:
  num_episodes: 10
  save_plot: evaluators/results/SF/masupgnn/best_eval.png
  show_plot: false
  animation: true
  event_driven: true
  max_frames: 2000
