#   python evaluators/test.py --env_config configs/eval/masupgnn/masup_gnn_tsp12.yaml --model models/xxx/final
env_type: masup_gnn

env:
  graph_path: graphs/simple_TSP_12.json
  enable_wait: true
  norm_reward: true
  deltaT: 0.333
  num_agents: 3
  init_positions: [0, 5, 11]
  episode_len: 300
  custom_configs:
    T: 20.0
    role_imformation: decision
    truncate_by_time: true
    node_feat_dim: 2
    edge_feat_dim: 1
    global_feat_dim: 2

eval:
  num_episodes: 10
  save_plot: evaluators/results/TSP12/mappo_masupgnn/best_eval.png
  show_plot: False
  animation: True
  event_driven: true
  max_frames: 500
