#   python trainers/imitator/imitation_trainer.py --config configs/imitator/mappo_masup_SF.yaml
algo_name: mappo

env_type: masup
env_config: configs/eval/masup/masup_SF.yaml

actor_type: mlp

actor:
  hidden: [256, 256]

critic_hidden_sizes: [256, 256]

actor_lr: 3.0e-4
critic_lr: 3.0e-4
batch_size: 1024
iteration: 100
actor_patience: 5
actor_min_delta: 1.0e-5
use_value_norm: true

data_path: ~/autodl-tmp/dataset/SF/mappo_masup.h5
save_dir: models/imi-mappo-masup-SF
exp_name: imi_mappo_masup_mlp_SF
track: false
wandb_project: MAP-imitation
