#   python trainers/imitator/imitation_trainer.py \
#       --config configs/imitator/mappo_masup_mlp_island.yaml
#   python trainers/imitator/imitation_trainer.py \
#       --config configs/imitator/mappo_masup_mlp_island.yaml \
#       --data_path dataset/island/samples.h5
#   - Actor  (masup_mlp): BC cross-entropy loss on expert actions
algo_name: mappo

env_type: masup
env_config: configs/eval/masup/masup_marostica.yaml

actor_type: masup_mlp
critic_type: masup_mlp

actor:
  graph_path: graphs/marostica.json
  num_agents: 6
  num_nodes: 41
  role_imformation: decision
  gpe_dim: 8
  proj_dim: 16
  use_log_idleness: false
  T_time: 50.0
  hidden: [256, 512]

critic:
  graph_path: graphs/marostica.json
  num_agents: 6
  num_nodes: 41
  role_imformation: decision
  gpe_dim: 8
  proj_dim: 16
  use_log_idleness: false
  T_time: 50.0
  input_mode: state
  hidden: [256, 512]

actor_lr: 1.0e-4
critic_lr: 1.0e-4
batch_size: 4096
iteration: 40
actor_patience: 5
actor_min_delta: 1.0e-5
use_value_norm: true

data_path: /root/autodl-tmp/dataset/marostica/dtassi_samples.h5
save_dir: models/imi-mappo-pre-masup-marostica
exp_name: imi_pre_masup_mlp_mappo_marostica
track: false
wandb_project: MAP-imitation
