#   python trainers/imitator/imitation_trainer.py \
#       --config configs/imitator/mappo_masup_mlp_SF.yaml
#   python trainers/imitator/imitation_trainer.py \
#       --config configs/imitator/mappo_masup_mlp_SF.yaml \
#       --data_path dataset/SF/samples.h5
#   - Actor  (masup_mlp): BC cross-entropy loss on expert actions
algo_name: mappo

env_type: masup
env_config: configs/eval/masup/masup_SF.yaml

actor_type: masup_mlp
critic_type: masup_mlp

actor:
  graph_path: graphs/SFcrimemap.json
  num_agents: 3
  num_nodes: 12
  role_imformation: decision
  gpe_dim: 8
  proj_dim: 16
  use_log_idleness: false
  T_time: 150.0
  # T_time: 200.0
  hidden: [256, 256]

critic:
  graph_path: graphs/SFcrimemap.json
  num_agents: 3
  num_nodes: 12
  role_imformation: decision
  gpe_dim: 8
  proj_dim: 16
  use_log_idleness: false
  T_time: 150.0
  # T_time: 200.0
  input_mode: state
  hidden: [256, 256]

actor_lr: 3.0e-4
critic_lr: 3.0e-4
batch_size: 4096
iteration: 20
actor_patience: 5
actor_min_delta: 1.0e-5
use_value_norm: true

data_path: ~/autodl-tmp/dataset/SF/mappo_masup.h5
save_dir: models/imi-mappo-pre-masup-SF_075T
exp_name: imi_pre_masup_mlp_mappo_SF_075T
track: false
wandb_project: MAP-imitation
