#   python trainers/imitator/imitation_trainer.py --config configs/imitator/masup_mlp_grid.yaml
#   python trainers/imitator/imitation_trainer.py --config configs/imitator/masup_mlp_grid.yaml --data_path dataset/grid/samples.h5
algo_name: mappo

env_type: masup
env_config: configs/eval/masup/masup_grid.yaml

actor_type: mlp

actor:
  hidden: [256, 512]

critic_hidden_sizes: [256, 512]

actor_lr: 3.0e-4
critic_lr: 3.0e-4
batch_size: 8192
iteration: 30
actor_patience: 5
actor_min_delta: 1.0e-5
use_value_norm: true

data_path: /root/autodl-tmp/dataset/grid/dtassi_6a_samples.h5
save_dir: models/imi-mappo-masup-grid-6a
exp_name: imi_mappo_masup_grid_6a
track: false
wandb_project: MAP-imitation
