#   python trainers/imitator/imitation_trainer.py \
#       --config configs/imitator/mappo_masup_marostica.yaml
#   python trainers/imitator/imitation_trainer.py \
#       --config configs/imitator/mappo_masup_marostica.yaml \
#       --data_path /root/autodl-tmp/dataset/marostica/dtassi_samples.h5
#   - Actor  (mlp): BC cross-entropy loss on expert actions
algo_name: mappo

env_type: masup
env_config: configs/eval/masup/masup_marostica.yaml

actor_type: mlp

actor:
  hidden: [256, 512]

critic_hidden_sizes: [256, 512]

actor_lr: 1.0e-4
critic_lr: 1.0e-4
batch_size: 8192
iteration: 35
actor_patience: 5
actor_min_delta: 1.0e-5
use_value_norm: true

data_path: /root/autodl-tmp/dataset/marostica/baps_6a_samples.h5
save_dir: models/imi-mappo-mlp-masup-marostica
exp_name: imi_pre_mlp_mappo_masup_marostica
track: false
wandb_project: MAP-imitation
