#   python trainers/imitator/imitation_trainer.py --config configs/imitator/masup_mlp_ippo_grid.yaml
#   python trainers/imitator/imitation_trainer.py --config configs/imitator/masup_mlp_ippo_grid.yaml --data_path dataset/grid/samples.h5
#   - Actor: BC loss (cross-entropy on expert actions)
algo_name: ippo

env_type: masup
env_config: configs/eval/masup/masup_grid.yaml

actor_type: mlp

actor:
  hidden: [512, 256, 128]

critic_hidden_sizes: [512, 256, 128]

actor_lr: 3.0e-4
critic_lr: 3.0e-4
batch_size: 1024
iteration: 100
actor_patience: 5
actor_min_delta: 1.0e-5
use_value_norm: true

data_path: dataset/grid/samples_pure_0.01reward_random.h5
save_dir: models/masup-mlp-ippo-imitation
exp_name: imi_masup_mlp_ippo_grid
track: false
wandb_project: MAP-imitation
