#   python trainers/imitator/imitation_trainer.py --config configs/imitator/masup_mlp_qmix.yaml
algo_name: qmix

env_type: masup
env_config: configs/eval/masup/masup_grid.yaml

q_type: mlp

q_network:
  hidden: [256, 256]
  dueling: false

actor_lr: 3.0e-4
bc_lambda: 1.0
value_lambda: 0.5
batch_size: 1024
iteration: 100
use_value_norm: true

data_path: dataset/grid/samples_pure_0.01reward_random.h5
save_dir: models/masup-mlp-qmix-imitation
exp_name: imi_masup_mlp_qmix
track: false
wandb_project: MAP-imitation
