#   python trainers/imitator/imitation_trainer.py --config configs/imitator/masup_mlp_vdn.yaml
algo_name: vdn

env_type: masup
env_config: configs/eval/masup/masup_grid.yaml

q_type: mlp

q_network:
  hidden: [512, 256, 128]
  dueling: false

actor_lr: 3.0e-4
bc_lambda: 1.0
value_lambda: 0.5
batch_size: 1024
iteration: 40
use_value_norm: true

data_path: dataset/grid/mappo_masup_a6.h5
save_dir: models/vdn-masup-grid-imi
exp_name: imi_masup_vdn
track: false
wandb_project: MAP-imitation
