#   python trainers/imitator/imitation_trainer.py --config configs/imitator/masup_mlp_vdppo.yaml
algo_name: vdppo

env_type: masup
env_config: configs/eval/masup/masup_grid.yaml

actor_type: mlp

actor:
  hidden: [512, 256, 128]


actor_lr: 3.0e-4
batch_size: 1024
iteration: 30
actor_patience: 5
actor_min_delta: 1.0e-5
use_value_norm: false

data_path: dataset/grid/mappo_masup_a6.h5
save_dir: models/vdppo-masup-grid-imi
exp_name: imi_masup_vdppo
track: false
wandb_project: MAP-imitation
