_wandb:
    value:
        cli_version: 0.24.0
        e:
            znqhvze5dnpnnvtq3ag49vsv49suvmye:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "493078765568"
                        used: "102771097600"
                email: zihengwang726@gmail.com
                executable: /home/spikew/miniconda3/envs/Patrolling/bin/python
                git:
                    commit: fb0a436872408a294190571edfb34880bf0db1b9
                    remote: git@github.com:SpikeW726/MAP-imitation-framework.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-5a74b3b0-acf3-d669-bdd9-1d423f1a52e9
                host: ASUS
                memory:
                    total: "16373432320"
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.35
                program: /home/spikew/MAP/MAP-imitation-framework/main.py
                python: CPython 3.10.19
                root: /home/spikew/MAP/MAP-imitation-framework
                startedAt: "2026-01-27T16:42:36.869548Z"
                writerId: znqhvze5dnpnnvtq3ag49vsv49suvmye
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 35
            "4": 3.10.19
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
clip_range:
    value: 0.2
ent_coef:
    value: 0.1
gae_lambda:
    value: 1
gamma:
    value: 0.999
lr:
    value: 3e-05
num_envs:
    value: 4
num_minibatches:
    value: 4
num_steps:
    value: 128
total_timesteps:
    value: 500000
update_epochs:
    value: 10
vf_coef:
    value: 0.5
